# (PART) Data Analytics {-} 

# 데이터 분석 이용 사례 {#DataAnalyticsUseCases}

*Chapter lead: David Madigan*

OHDSI는 실세계 헬스케어 데이터 (일반적으로 보험청구 또는 의무기록 데이터베이스) 로부터 믿을만한 근거를 만들어내는 데 초점을 맞춰 왔다. OHDSI가 관심을 가져온 이용 사례들은 크게 3개의 카테고리로 구분된다:

- 특성 분석
- 인구 수준 추정
- 환자 수준 예측

본 장에서는 각 카테고리에 관해 설명한다. 모든 이용 사례들에 있어서, 생성된 근거들은 데이터 자체가 가지고 있는 한계를 이어받는다는 점을 유념하십시오. 이 한계들에 대해서는 이 책의 "근거의 질" 장에서 다루고 있다. (\@ref(EvidenceQuality)장 ~ \@ref(MethodValidity)장)

## 특성 분석

\index{characterization}

특성 분석은 다음과 같은 질문에 답변을 시도한다.

> 그들에게 무슨 일이 발생했는가?

우리는 데이터를 이용하여 코호트 또는 전체 데이터베이스 내 환자들과 헬스케어의 특성을 묻는 말에 답할 수 있으며, 시간이 지남에 따라 이 특성들이 어떻게 변화하는지 알 수 있다.

데이터는 다음과 같은 질문에 답을 제공할 수 있다:

- 심방세동으로 새 진단을 받은 환자 중 얼마나 많은 사람이 와파린을 처방받는가?
- 고관절 치환술을 받은 환자들의 평균 연령은 어떻게 되는가?
- 65세 이상 환자 중 폐렴 발생률은 얼마나 되는가?

일반적인 특성 분석 질문들은 다음과 같이 표현된다:

- 얼마나 많은 환자가...?
- 얼마나 자주...?
- 환자 중 어느 정도의 비율이...?
- ... 검사에 대한 결과값의 분포가 어떠한가?
- ... 질병을 가진 환자들의 당화혈색소(HbA1c) 수준이 어떠한가?
- ... 환자들에 대한 검사 결과값이 어떠한가?
- 환자가 ...에 노출되는 평균 노출 기간은 얼마인가?
- ...의 시간 경과에 따른 추세는 무엇인가?
- 이 환자들이 사용하는 다른 약들이 무엇인가?
- 수반되는 치료법들이 무엇인가?
- ...에 대한 충분한 증례가 있는가?
- ...에 대한 연구 X가 실행 가능한가?
- ...에 대한 인구통계학적 특징은 무엇인가?
- ...의 위험인자들이 무엇인가? (특정 위험인자가 구분된다면, 이는 예측이 아닌 추정에 해당함)
- ...의 예측요인들이 무엇인가?


그리고 원하는 결과값은 다음과 같다:

- 건수 또는 퍼센트(count or percentage)
- 평균(averages)
- 기술 통계(descriptive statistics)
- 발생률(incidence rate)
- 유병률(prevalence)
- 코호트(cohort)
- 규칙 기반 표현형(rule-based phenotype)
- 약물 사용(drug utilization)
- 질병의 자연 경과(disease natural history)
- 순응도(adherence)
- 동반 질환 프로파일(co-morbidity profile)
- 치료 경로(treatment pathways)
- 치료 요법(line of therapy)

## 인구 수준 추정

\index{population-level estimation}

제한된 범위내에서, 데이터는 헬스케어 개입 효과에 대한 인과적 추론을 지원함으로써 질문에 답할 수 있다.

> 무엇이 인과 효과 causal effect인가?

우리는 행동의 결과를 이해하기 위해 인과 효과를 파악하고자 한다. 예를 들어, 우리가 어떤 치료법을 사용하기로 했다면, 이것이 앞으로 우리에게 무슨 변화를 일으킬까?

데이터는 다음과 같은 질문에 답을 줄 수 있다:

- 새로 심방세동으로 진단받은 환자들에 있어서, 치료 시작한 지 1년 이내에 와파린 warfarin이 다비가트란 dabigatran 보다 주요 출혈을 더 일으키는가?
- 메트포르민 metformin이 설사에 미치는 인과 효과가 연령에 따라 다른가?

일반적인 인구 수준 효과 추정 질문들은 다음과 같이 표현된다:

- ...의 효과는 무엇인가?
- 내가 개입한다면 어떻게 될까...?
- 어떤 치료가 더 효과가 좋을까?
- X가 Y에 미치는 위험이 무엇일까?
- ... 이벤트 발생에 걸리는 시간 time-to-event가 얼마나 될까?

그리고 원하는 결과값은 다음과 같다:

- 상대 위험도(relative risk)
- 발생 위험비(hazards ratio)
- 대응위험도/교차비(odds ratio)
- 평균 처치 효과(average treatment effect)
- 인과적 영향(causal effect)
- 관련성(association)
- 상관성(correlation)
- 안전성 감시(safety surveillance)
- 비교 효과(comparative effectiveness)

## 환자 수준 예측

\index{patient-level prediction}

데이터베이스에 쌓인 환자 건강 이력을 기반으로, 우리는 미래에 발생할 건강 이벤트에 대해 환자 수준의 예측할 수 있다.

> 나에게 무슨 일이 발생할까?

데이터는 다음과 같은 질문에 답을 제공할 수 있다:

- 주요 우울증으로 새롭게 진단받은 특정 환자가 진단받은 지 1년 안에 자살을 시도할 확률이 얼마나 되는가?
- 심방세동으로 새롭게 진단받은 특정 환자가, 와파린으로 치료를 시작한 지 1년 안에 허혈성 뇌졸중을 겪을 확률이 얼마나 되는가?

일반적인 환자 수준 예측에 대한 질문들은 다음과 같이 표현된다:

- 이 환자가 ...할 가능성이 얼마나 되는가?
- ...에 대한 후보자들이 누구인가?

그리고 원하는 결과값은 다음과 같다:

- 개인에 대한 확률
- 예측 모델
- 높은/낮은 위험군
- 확률론적 표현형

인구 수준 추정과 환자 수준 예측은 어느 정도 중복된다. 예측을 위한 중요 이용사례로 다음 예제를 들 수 있다: 약물 A가 처방된 특정 환자의 임상 결과를 예측하는 것과 또한 약물 B가 처방된 사람에게서 그와 똑같은 임상 결과를 예측하는 것이다. 실제로 한 환자가 여러 약 중 하나 (약물 A이라고 하자) 를 처방받았고, 약물 A의 예상되는 결과가 실제로 일어나는지를 살펴봤다고 가정해 보자. 그 환자에게 약물 B는 처방되지 않았고 B 투여 이후의 임상 결과는 관찰된 적이 없으므로 그 예상된 임상 결과는 반 사실적 (counterfactual)이며, 예측은 할 수 있더라도 사실과 다를 수 있다. 이러한 각각의 예측 작업은 환자 수준 예측에 속한다. 그러나 두 결과의 차이 (또는 비율) 는 단위 수준의 *인과* 효과이며, 예측모형이 아닌 인과적 영향 추정 방법론을 사용하여 추정하여야 한다.

```{block2, type='rmdimportant'}
사람들은 예측모델을 인과 모델로 잘못 해석하는 경향이 있다. 그러나 예측 모델은 상관성만을 보여줄 수 있으며 결코 인과성을 보여줄 수 없다. 예를 들자면, 당뇨병이 심근경색의 강한 예측변수이기 때문에, 당뇨병 약을 사용하는 것은 심근경색의 강한 예측변수일 수 있다. 그러나 이것이 당뇨병 약 복용을 중단하는 것이 심근경색을 막는다는 것을 의미하는 것은 아니다!
```

## 고혈압 이용 사례 예

당신은 고혈압의 1차 치료 요법으로서 ACE 억제제 단일요법과 타이아자이드 이뇨제 단일요법이 급성 심근경색과 혈관부종에 미치는 영향을 연구하는 데 관심이 있는 연구자이다. 당신은 OHDSI 연구에 기반하여 인구 수준 추정 연구 질문을 도출했지만, 먼저 관심이 있는 특정 치료에 대한 특성을 어떻게 분석할 것인지 해결해야 한다.

### 특성 분석 질문

급성 심근경색은 고혈압 환자들에게 일어날 수 있는 심혈관계 합병증으로, 고혈압에 대한 효과적인 치료로 이 위험을 줄여야 한다. 혈관부종은 희귀하지만, 잠재적으로 심각한 ACE 억제제의 알려진 부작용이다. 당신은 관심 약제 (ACE 억제제와 티아자이드 이뇨제) 들에 노출된 코호트 (\@ref(Cohorts)장 참고) 를 생성하는 것으로부터 연구를 시작한다. 노출된 환자들의 인구통계학적 정보, 병적 상태, 병용 약물 등 기저 특성을 파악하기 위하여 특성 분석 (\@ref(Characterization)장 참고) 을 수행한다. 또한 이 노출 환자 내에서 분석하고자 하는 결과가 얼마나 발생하는지 추정하는 또 다른 특성 분석을 수행한다. 그리고, 당신은 ‘얼마나 자주 1) 급성 심근경색과 2) 혈관부종이 ACE 억제제와 티아자이드 이뇨제에 노출된 기간 동안 발생하는가?’를 묻게 된다. 이러한 특성 분석은 인구 수준 추정 연구 수행의 실현 가능성을 판단하게 하고, 두 치료군이 비교 가능한지를 평가하게 하며, 환자들이 받는 치료에 예측되는 위험 요소들을 파악할 수 있게 한다. 

### 인구 수준 추정에 대한 질문

인구 수준 효과 추정 연구 (\@ref(PopulationLevelEstimation)장 참고) 는 ACE 억제제와 티아자이드 이뇨제가 급성 심근경색과 혈관부종에 미치는 상대 위험을 추정한다. 더 나아가, 분석에 대한 평가와 음성대조군 분석을 통해 우리가 평균 치료 효과에 대해 믿을 만한 추정치를 도출했는지 평가한다.

### 환자 수준 예측에 대한 질문

당신은 노출의 인과적 영향 여부와 상관없이, 가장 위험한 결과에 처한 환자들을 알아내고자 할 수 있다. 이것은 환자 수준 예측 (\@ref(PatientLevelPrediction)장 참고) 의 문제이다. ACE 억제제를 처음 사용하는 환자 중 치료 시작한 지 1년 동안 급성 심근경색 발병 위험이 가장 높은 환자들을 찾아내는 예측 모델을 개발한다고 생각해 보십시오. 이 모델을 통해 우리는 처음으로 ACE 처방을 받은 환자의 병력에서 관찰된 사건을 바탕으로, 향후 1년 동안 급성 심근경색을 겪을 가능성을 예측할 수 있다.

## 관찰 연구의 한계

\index{limitations of obervational research}

OHDSI 데이터베이스가 답변을 제공할 수 없는 중요한 의료분야 질문들이 많이 존재한다. 아래 질문들이 이에 해당한다:

- 위약과 비교한 치료의 인과 효과. 때때로 치료군의 인과 효과를 비치료군과 비교하여 분석하는 것은 고려해 볼 수 있지만 위약군과 비교하려고 해서는 안 된다.
- 처방전 없이 구입할 수 있는 일반 의약품과 관련된 모든 것 
- 많은 임상 결과와 여러 변수가 아주 성기게 기록된 경우. 사망률, 행동 결과, 라이프 스타일 및 사회-경제적 지위와 같은 것들이 이에 포함된다.
- 환자는 건강이 좋지 않을 때만 의료 시스템을 이용하는 경향이 있기 때문에, 치료의 이점을 측정하기가 쉽지 않다.

### 잘못된 데이터

OHDSI 데이터베이스에 기록된 임상 데이터는 의료 현실과 차이가 있을 수 있다. 예를 들어, 환자가 심근경색을 경험한 적이 없어도 환자의 기록에 심근경색 코드가 포함되어 있을 수 있다. 마찬가지로 검사 값이 잘못되었거나 시술에 대한 잘못된 코드가 데이터베이스에 저장되었을 수도 있다. \@ref(DataQuality)장과 \@ref(ClinicalValidity)장은 이와 같은 이슈들을 다루고 있으며, 모범 사례를 통해 이러한 문제들을 최대한 식별하고 수정하고자 한다. 그런데도, 잘못된 데이터는 필연적으로 어느 정도까지 존재할 수밖에 없으며, 분석의 타당성을 약화시킬 수 있다. 매우 많은 문헌이 데이터 오류들을 처리하기 위한 통계적 추론 보정에 초점을 맞추고 있다. - 예를 들어 @fuller2009measurement 참조

### 결측 데이터

\index{missing data}

OHDSI 데이터베이스에서의 결측은 감지하기 어려운 문제점들을 낳는다. 데이터베이스에 기록되어야 하는 건강 이벤트 (예를 들어 처방, 검사 값 등) 가 기록되지 않은 것, 그것이 “결측”이다. 통계 문헌들은 “임의의 완전 결측”, “임의의 결측”, “임의가 아닌 결측”과 같은 결측 유형들과 이러한 유형들을 다루는 복잡한 방법론들을 구별하고 있다. @perkins2017principled 가 이 주제에 대한 유용한 입문서를 제공한다.

## 요약

```{block2, type='rmdsummary'}
- 관찰 연구의 이용 사례들은 크게 3개의 카테고리로 구분된다.

- **특성 분석**은 “그들에게 무슨 일이 발생했는가?”라는 질문에 답하는 것을 목적으로 한다.

- **인구 수준 추정**은 “인과적 영향이 무엇인가?”라는 질문에 답하는 것을 목적으로 한다.

- **환자 수준 예측**은 “나에게 무엇이 일어날까?”라는 질문에 답하는 것을 목적으로 한다.

- 예측 모델은 인과 모델이 아니다; 강한 예측변수를 통제하는 것이 결과에 영향을 미칠 것이라고 믿을 근거가 없다.

- 관찰형 의료 데이터를 이용하여 연구할 수 없는 질문들도 있다.

```

## 예제

```{exercise, exerciseUseCases1}
다음 질문들은 어떤 사용 사례 카테고리에 해당하는가?

1. 비스테로이드 약물에 최근 노출되었던 환자들이 위장관 출혈을 겪을 비율을 계산하십시오.

2. 기저 특성을 기반으로 특정 환자가 차년도에 위장관 출혈을 겪을 확률을 계산하십시오.

3. 셀레콕시브 celecoxib와 비교하여 디클로페낙 diclofenac이 위장관 출혈에 미치는 위험을 추정하십시오.

```

```{exercise, exerciseUseCases2}
당신은 디클로페낙 diclofenac이 위장관 출혈에 미치는 위험을 비노출 (위약) 의 경우와 비교하여 추정하고자 한다. 이와 같은 연구가 헬스케어 관찰 데이터를 이용하여 수행 가능한가?

```

제안된 답변은 부록 \@ref(UseCasesanswers)에서 확인할 수 있다.
