# (APPENDIX) Appendix {-}

# Glossary {#Glossary}

ACHILLES
: 데이터베이스 수준의 특성 보고서. 

ARACHNE
: 연합 네트워크의 조정 및 실행을 위해 개발중인 OHDSI 플랫폼.

ATLAS
: 환자 수준 임상 데이터로부터 실제 근거를 생성하기 위한 관찰 분석의 실행과 설계를 지원하기 위하여 참여 사이트에 설치된 웹 기반 어플리케이션.

편향 (Bias)
: 오류의 예상 값 (실제 값과 예상 값의 차이).

부울 (Boolean)
: 오직 두개의 값만 가지는 변수 (참 혹은 거짓).

Care site
: 의료 서비스 제공을 실천하는 고유하게 식별된 기관 (물리적 혹은 조직적) 단위 (사무실 병동, 병원, 클리닉 등).

환자 대조군 (Case control)
: 인구-수준 효과 추정을 위한 회고 연구 설계(retrospective study design)의 유형. 환자 대조군 연구는 표적 결과와의 "사례(cases)"를 표적 결과가 없는 "대조(controls)"로 일치시킨다. 그 후 이전의 시간을 살펴보고 사례와 대조의 노출 오즈(odds)를 비교한다.

인과적 영향 (Causal effect)
: 인구 수준 추정이 그 자체로 얼마나 영향을 미치는가에 대한 것. 한 가지 정의는 "인과적 영향"를 표적 인구 안 "단위 수준(unit-level) 인과적 영향"의 평균으로 일치시킨다. 단위 수준 인과적 영향은 노출된 개인의 결과와 노출되지 않은 개인의 결과 간의 대조이다 (혹은 B에 대응하여 A에 노출된 적이 있는지).

특성 (Characterization)
: 코호트 혹은 전체 데이터베이스의 서술적 연구. \@ref(Characterization)장 참조.

청구 자료 (Claims data)
: 의료 보험 회사에게 청구하기 위한 목적으로 생성된 데이터

임상 시험 (Clinical trial)
: 중재(Interventional) 임상 연구.

코호트 (Cohort)
: 특정 기간 동안 하나 혹은 다수 기준의 포함을 만족시키는 사람들의 집합. \@ref(Cohorts)장 참조.

Concept
: 의학 전문 용어에 정의된 용어 (코드 포함) (예를 들어, SNOMED CT ). \@ref(StandardizedVocabularies)장 참조.

Concept 세트
: concept 세트는 다양한 분석에서 재사용 가능한 요소들로 사용될 수 있는 concept의 목록을 나타내는 표현. \@ref(Cohorts)장 참조.

공통 데이터 모델 (Common Data Model, CDM)
: 분석의 이식성을 허용하는 의료 데이터를 대표하는 조약 (수정되지 않은 동일한 분석을 여러 데이터 세트에서 실행할 수 있다). \@ref(CommonDataModel)장 참조.

비교 효과 (Comparative Effectiveness)
: 관심 결과에 대한 두 개의 다른 노출의 영향 비교. \@ref(PopulationLevelEstimation)장 참조.

조건 (Condition)
: 제공자가 진찰하거나 환자가 보고한 진단, 기호, 혹은 증상.

교란 (Confounding)
: 교란은 주요 관심 노출이 결과와 관련된 몇가지 다른 사실이 섞일 때 일어나는 연관성 예상 측정 안의 왜곡 (불확실성) 이다.

변수 (Covariate)
: 독립적 변수로 통계적 모델에 사용되는 데이터 요소 (예를 들어, 체중).

데이터 질 (Data quality)
: 데이터를 특정 용도에 적합하게 만드는 완전성, 유효성, 일관성, 적시성 및 정확성의 상태.

의료 기기 (Device)
: 화학 작용을 넘어서는 매커니즘을 통해 진단 또는 치료 목적으로 사용되는 대외 물리적 물체 혹은 기구. 의료 기기는 이식할 수 있는 물체 (예를 들면, 심박조정기, 스텐트, 인공 관절 등), 의료 장비 및 보급품 (예를 들어, 붕대, 목발, 주사기), 의료 절차에 사용되는 기구 (예를 들어, 봉합, 제세동기) 그리고 임상 치료에 사용되는 재료 (예를 들어, 접착제, body 재료, 치과용 재료, 수술용 재료)를 포함한다.

약물 (Drug)
: 약물은 사람에게 투여할 때 특정한 화학 반응을 발휘 할 수 있도록 조제된 생화학 물질이다. 약물은 처방전 및 처방전 없이 구입 가능한 약물, 백신, 그리고 대용량 molecule 생물학적 치료법을 포함한다. 국소 부위에 섭취되거나 접촉되는 방사선 기기는 약물로 간주되지 않는다.

도메인 (Domain)
: 도메인은 CDM 표의 표준화된 필드에 대해 허용하는 concept의 세트를 정의한다. 예를 들어, "조건" 도메인은 환자의 컨디션을 설명하는 concept을 포함하고, 이 concept는 CONDITION_OCCURRENCE와 CONDITION_ERA 테이블의 condition_concept_id 필드에만 저장된다.

전자 의무기록 (Electronic Health Record, EHR)
: 전자기록 시스템에 기록되고 치료 기간동안 생성된 데이터를 의미한다.

역학 (Epidemiology)
: 정의된 인구의 건강 및 질병 조건의 분포, 패턴, 결정의 연구.

근거 중심 의학 (Evidence-based medicine)
: 개인의 환자 관리에 대한 의사 결정의 경험적, 과학적 근거의 사용.

추출-변환-적재 (Extract-Transform-Load, ETL)
: 한 형식에서 다른 형식으로 데이터를 변환하는 과정, 예를 들어 원천 포맷을 CDM으로 변환한다. \@ref(ExtractTransformLoad)장 참조.

짝짓기 (Matching)
: 많은 인구-수준 효과 추정은 노출의 인과적 영향을 노출된 환자의 결과를 노출되지 않은 환자의 동일한 결과로 비교함으로써 식별하는 것을 시도한다 (혹은 A를 B의 대립으로 노출시킨다).이 두 환자 집단은 노출 이외의 방식이 다를 수 있으므로, "짝짓기"는 최소한 측정된 환자 특성과 관련하여 최대한 비슷한 노출된 환자 그룹 및 노출되지 않은 환자 그룹을 생성하기 위해 시도한다.

측정 (Measurement)
: 개인 혹은 개인의 표본에 대한 체계적이고 표준화된 검사 혹은 학습을 통하여 얻어진 구조적 값 (숫자 혹은 범주형).

측정 오차 (Measurement error)
: 기록된 측정 (혈압, 환자 연령, 치료 기간) 이 해당 참 측정과 다를 때 발생한다.

메타데이터 (Metadata)
: 다른 데이터에 대한 정보를 제공하고 기술하는 데이터의 집단이다. 이것은 구체적 메타데이터, 구조적 메타데이터, 관리 메타데이터, 참조 메타데이터, 통계적 메타데이터를 포함한다.

Methods Library
: 관찰 연구를 수행하기 위하여 OHDSI공동체에 의해 개발된 R 패키지의 집단.

Model misspecification
: 많은 OHDSI 방법은 비례 위험 회귀 또는 무작위 forest와 같은 통계적 모델을 채택한다. 데이터를 생성한 메커니즘이 가정된 모델에서 벗어나는 한, 모델은 "불특정"이 된다.

음성 통제 결과 (Negative control)
: 노출이 결과를 방지하거나 유발하지 않는다고 믿어지는 노출-결과 쌍. 효과 추정 방법이 생성하는 결과가 진실인지 여부를 판단하는데 사용될 수 있다. \@ref(MethodValidity)장 참조.

관찰 (Observation)
: 검사, 질의 혹은 절차의 내용에서 얻어진 개인에 대한 임상적 사실.

관찰 기간 (Observation period)
: 실제로 어떤 사건도 기록되지 않더라도 원천 시스템 내에서 임상 사건을 가질 위험이 있는 사람을 기록하는 시간 (헬스케어 상호작용이 없는 건강한 환자).

관찰 연구 (Observational study)
: 연구자가 개입에 대한 통제력이 없는 연구.

OHDSI SQL
: SqlRender R 패키지를 사용하여 다른 다양한 SQL 언어로 자동 변환이 가능한 SQL 언어. OHDSI SQL은 대부분 SQL 서버 SQL의 하위 세트이지만, 추가적인 매개변수화를 허용한다. \@ref(SqlAndR)장 참조.

오픈 사이언스 (Open science)
: 과학적 연구와 (간행물, 데이터, 물리적 표본, 소프트웨어) 그것을 사회, 아마추어, 프로페셔널의 모든 계층이 접근 가능할 수 있게 보급할 수 있는 운동. \@ref(OpenScience)장 참조.

결과 (Outcome)
: 분석의 초점을 제공하는 관찰. 예를 들어, 환자 수준 예측 모델은 결과 "stroke"를 예측할 수도 있다. 혹은 인구 수준 추정은 약물이 결과 "두통"에 미치는 인과적 영향을 예측할 수 있다.

환자 수준 예측 (Patient-level prediction)
: 기저 특성에 기반한 몇 미래 결과의 경험의 환자 특정 가능성을 생성하기 위한 예측 모델의 어플리케이션과 개발.

표현형 (Phenotype)
: 물리적 특성에 대한 설명. 이것은 체중과 머리 색 뿐만 아니라 전체 건강, 질병 기록 그리고 행동과 같은 시각적인 특성을 포함한다.

인구 수준 추정 (Population-level estimation)
: 인과적 영향에 대한 연구. 평균 (인구 수준) 영향 크기를 추정한다.

양성 통제 결과 (Negative control)
: 노출이 결과를 유발하거나 방지하는 것으로 믿어지는 노출 결과 쌍. 효과 추정 방법이 생성하는 결과가 진실인지 여부를 판단하는데 사용될 수 있다. \@ref(MethodValidity)장 참조.

절차 (Procedure)
: 진단 혹은 치료 목적으로 의료 제공자가 환자에게 지시하거나 수행하는 활동 혹은 과정.

성향 점수 (Propensity score, PS)
: 인구의 균형을 맞추기 위한 인구 수준 추정에 사용되는 단일 행렬. 이는 관찰 연구의 두 치료 그룹간의 무작위화를 모방하기 위함이다. PS는 관심 치료를 받은 환자의 가능성을 관찰된 기저 공변량 세트의 기능으로 나타낸다. 이는 대부분 로지스틱 회귀분석을 사용하여 계산되는데, 이는 이항 결과가 표적 치료를 받는 집단은 1로, 대조군 치료의 경우 0으로 설정한다. \@ref(PopulationLevelEstimation)장 참조.

프로토콜 (Protocol)
: 연구 설계를 완전히 지정하는 사람이 읽을 수 있는 문서.

Rabbit-in-a-Hat
: ETL을 원천 형식에서 CDM으로 정의하는 것을 도와주는 상호적인 소프트웨어 툴. White Rabbit으로 생성된 데이터베이스 개요를 입력값으로 사용한다. 7장 참조.

선택 편향 (Selection bias)
: 데이터 안의 환자 집합이 통계적 분석이 왜곡되는 방식으로 인구 안의 환자로부터 벗어날 때 발생하는 편향.

자가제어 설계(Self-controlled designs)
: 같은 환자 안에서 다른 노출이 진행되는 동안 결과를 비교하는 연구 설계.

민감도 분석 (Sensitivity analysis)
: 어떤 불확실성이 존재하는가에 대한 분석 선택의 영향을 평가하기 위한 연구에 사용되는 주요 분석의 변이

SNOMED
: 임상 문서와 보고에 사용되는 코드, 용어, 동의어와 정의를 제공하는 시스템적으로 조직적이고 체계적인 의학 용어 모음집.

연구 진단 (Study diagnostics)
: 주어진 분석 접근법이 주어진 연구 질문에 답하기 위해 사용될 수 있는가에 대한 여부를 결정하는 것이 목표인 분석 단계의 세트. \@ref(MethodValidity)장 참조.

연구 패키지 (Study package)
: 연구를 완전히 실행할 수 있는 컴퓨터 실행 프로그램. \@ref(SoftwareValidity)장 참조.

원천 코드(Source code)
: 원천 데이터베이스에서 사용하는 코드. 예를 들어 ICD-10 코드가 있다.

표준 concept (Standard Concept)
: 유효한 concept으로 설계되고 CDM에 나타날 수 있는 concept.

THEMIS
: CDM 모델 사양과 관련하여 더욱 세밀하고 상세한 표적 데이터 형식을 설명하는 OHDSI 워크그룹.

방문 (Visit)
: 개인이 건강 관리 시스템 내 주어진 환경의 진료소에서 한명 혹은 그 이상의 제공자로부터 의료 서비스를 지속적으로 받는 기간.

용어 (Vocabulary)
: 단어의 목록과 종종 사용되는 구로, 보통 알파벳 순으로 정렬되거나 정의되고 혹은 번역된다. \@ref(StandardizedVocabularies)장 참조.

White Rabbit
: ETL을 CDM으로 정의하기 전에 데이터베이스를 수집하기 위한 소프트웨어 툴. \@ref(ExtractTransformLoad)장 참조.
